# Generated by Django 4.0 on 2023-02-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='hashtag',
            field=models.ManyToManyField(to='testing.HashTag'),
        ),
    ]
