# Generated by Django 4.0 on 2023-02-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_rename_category_settest_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settest',
            name='sort',
            field=models.CharField(default='', max_length=16),
        ),
    ]
