# Generated by Django 4.0 on 2023-02-11 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_settest_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choise', to='testing.test'),
        ),
        migrations.AlterField(
            model_name='settestlist',
            name='set_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testing.settest'),
        ),
        migrations.AlterField(
            model_name='settestlist',
            name='test_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='choised', to='testing.testlist'),
        ),
    ]
