# Generated by Django 4.0 on 2023-02-11 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_settestlist_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settestlist',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tests', to='testing.test'),
        ),
    ]
