# Generated by Django 4.0 on 2023-02-14 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_alter_settestlist_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='link',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='nomber',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='settestlist',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='testing.test'),
        ),
    ]
