# Generated by Django 4.0 on 2023-03-20 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_category_link_test_nomber_alter_settestlist_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settestlist',
            name='set_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='testing.settest'),
        ),
    ]
